### ISSUE TITLE
MIPS R6 support tracker

### ISSUE THREAD

**Issue by KexyBiscuit** [AOSC-Dev/p-vector-rs#4]
- [tempfile](https://crates.io/crates/tempfile) v3.10.1 depends on…
  - [rustix](https://crates.io/crates/rustix) v0.38.31 depends on…
    - [libc](https://crates.io/crates/libc) v0.2.153 which doesn't include FS_IOC_* definitions until https://github.com/rust-lang/libc/pull/3591

`p-vector` now depends on patched versions of the above crates from AOSC-Tracking <https://github.com/AOSC-Dev/p-vector-rs/commit/d0ff8d9114a2774e95d4241b0363c9f9fa981c5b>, until…
- `rustix` updates `libc` dependency: <https://github.com/bytecodealliance/rustix/pull/1065>
  - `tempfile` updates to the updated version of `rustix`
  - No other dependencies still depend on old versions of `rustix`

**Comment by liushuyu** [comment]
Closing as won't fix due to MIPS r6 support being removed.
